### ISSUE TITLE
cannot import name Serializer

### ISSUE THREAD

**Issue by imseppl** [greedo/python-xbrl#21] opened 2015-08-21 20:43 UTC
Hi there, I have installed the latest version of marshmallow and when trying to run python-xbrl, I get this error:

>>> import xbrl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/xbrl/__init__.py", line 8, in <module>
    from .xbrl import XBRLParser, GAAP, GAAPSerializer, XBRLParserException
  File "/usr/local/lib/python2.7/dist-packages/xbrl/xbrl.py", line 5, in <module>
    from marshmallow import Serializer, fields
ImportError: cannot import name Serializer

**Comment by greedo** [comment] 2015-08-25 00:44
@imseppl could you post your `pip freeze` and any other relevant system environment information so I can replicate the issue

**Comment by greedo** [comment] 2015-08-25 04:37
@imseppl you are right looks like in [Marshmallow 1.0.0](https://marshmallow.readthedocs.org/en/latest/api_reference.html#marshmallow.fields.Nested.schema) they now use `Schema`

Should be fixed with ddc1d6984f5e14d8bc46d29dcc7be384c32ac569

**Closed by greedo** 2015-08-25 04:37 UTC

**Comment by imseppl** [comment] 2015-08-25 04:54
Thank you!!!

**Comment by ptibbetts** [comment] 2016-07-10 18:53
Hey @greedo, just ran into this again, installed using `pip install python-xbrl`, I don't think the PIP package has been updated to include this fix

**Comment by fnielsen** [comment] 2016-08-29 08:35
I can confirm that the PYPI package still has this fundamental problem with xbrl-1.1.0 and marshmallow-2.9.1.

**Comment by rschmard** [comment] 2016-09-22 21:56
I'm still having problems with the latest PYPI package too.  Has this been resolved?

**Comment by erm3nda** [comment] 2016-11-09 20:18
http://stackoverflow.com/a/33876061/2480481
